name: DBMGuiManager
version: '${version}'
main: com.wairesd.discordbm.addons.dbmguimanager.DBMGuiManager
api-version: '1.21'
authors: [1wairesd]

commands:
  opengui:
    description: Открыть тестовое GUI меню
    usage: /opengui