name: DBMGuiManager
version: '1.0'
main: com.wairesd.discordbm.addons.DBMGuiManager
api-version: '1.21'
authors: [1wairesd]

commands:
  opengui:
    description: Открыть тестовое GUI меню
    usage: /opengui