config:
  version: 1
  type: settings

DiscordBM:
  host:
    secret: "YourSercretCod"
    ip: "127.0.0.1"
    port: 8080
  server: "YourNameServer"
  debug:
    debug-registered-services: false
    debug-connections: false
    debug-client-responses: false
    debug-command-registrations: false
    debug-errors: true

