Discord:
  Bot-token: "your-bot-token"
  activity:
    type: "playing"
    message: "Velocity Server"

netty:
  port: 8080

forwarding-secret-file: "secret.complete.code"

view_connected_banned_ip: false

commands:
  default-ephemeral: false

buttons:
  timeout-ms: 900000

debug:
  debug-connections: true          # Logue customer connection and disconnecting
  debug-client-responses: false    # Logue requests and answers from customers
  debug-plugin-connections: true   # Login connecting plugins to customers
  debug-command-registrations: false # Log in the registration events of the teams
  debug-custom-command-registrations: true
  debug-sendmessage-action: false
  debug-authentication: true       # Log in authentication attempts and their results
  debug-errors: true               # Log in errors and exceptions