# settings.yml — settings configuration for DiscordBMV
# Documentation and examples: https://1wairesd.github.io/1wairesdIndustriesWiki/docs/DiscordBM/DiscordBMV/Configs/dscordbmv-main-settings
# If something is unclear — see the link above!

# settings.yml — настройка настроек для DiscordBMV
# Документация и примеры: https://1wairesd.github.io/1wairesdIndustriesWiki/docs/DiscordBM/DiscordBMV/Configs/dscordbmv-main-settings
# Если что-то не понятно — смотри по ссылке выше!

Discord:
  Bot-token: "your-bot-token"
  activity:
    type: "playing"
    message: "Velocity Server"

netty:
  ip : "127.0.0.1"
  port: 8080

forwarding-secret-file: "secret.complete.code"

view_connected_banned_ip: false

commands:
  default-ephemeral: false

buttons:
  timeout-ms: 900000

debug:
  debug-connections: true          # Logue customer connection and disconnecting
  debug-client-responses: false    # Logue requests and answers from customers
  debug-plugin-connections: true   # Login connecting plugins to customers
  debug-command-registrations: false # Log in the registration events of the teams
  debug-command-received: false     # Log received slash commands
  debug-command-execution: false    # Log custom command execution
  debug-resolved-messages: false    # Log resolved messages from placeholders
  debug-request-processing: false   # Log request/response processing with hook tracking
  debug-command-not-found: false    # Log warnings when commands are not found
  debug-sendmessage-action: false
  debug-sendmessage-to-channel: false
  debug-authentication: true       # Log in authentication attempts and their results
  debug-netty-start: false
  debug-errors: true               # Log in errors and exceptions
  debug-button-register: false

mysql:
  enabled: false           # true — использовать MySQL, false — использовать SQLite
  host: localhost
  port: 3306
  database: discordbmv
  username: root
  password: password
  params: '?useSSL=false&serverTimezone=UTC'
  # example:
  # jdbc:mysql://localhost:3306/discordbmv?user=root&password=password&useSSL=false&serverTimezone=UTC