velocity:
  secret: "YourSercretCod"
  host: "127.0.0.1"
  port: "8080"

server: "YourNameServer"

debug:
  debug-connections: false          # Logue connection and disconnects
  debug-client-responses: false    # Logue requests and answers from customers
  debug-command-registrations: false # Log in the registration events of the teams
  debug-errors: true              # Log in errors

